### ISSUE TITLE
Capture group

### ISSUE THREAD

**Issue by gogo9th** [kokke/tiny-regex-c#28]
Hi,

I am looking for a C source code for regular expression that supports finding matchings substrings for capture groups. I seems that tiny-regex-c doesn't support it... I wonder if you happen to know any other C libraries that support this feature. Thanks for your help.

**Comment by kokke** [comment]
Hi @gogo9th and thanks for checking out this library.

I don't know of other small libraries that support capture-groups, but I'm fairly certain that the PCRE library supports it. 

https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions
https://www.pcre.org/

Otherwise, I recommend that you check out the forks of this project, as some of them really have extended the functionality. There may be someone out there who have finished capture groups.
