### ISSUE TITLE
need help in finding one of the two strings.

### ISSUE THREAD

**Issue by sukhchainn** [kokke/tiny-regex-c#38]
I am having trouble finding the pattern to mach one of the two strings from a larger string.
`re_t match_pattern = re_compile("I|Me");`

The code above doesn't seem to work, what should I do?

**Comment by BenStigsen** [comment]
Not sure if the `or` symbol works. It's not in any of the tests, and this is in the README:
> Fix implementation of branches (|), and see if that can lead us closer to groups as well, e.g. (a|b)+.

So you could just match for `"I"` first, if not valid, match for `"Me"` after.

**Comment by sukhchainn** [comment]
Can you suggest me a minimal regex library that supports` or` in groups?

**Comment by BenStigsen** [comment]
I have not found a "good" one yet. This is the closest to it that I've found so far.

**Comment by kokke** [comment]
Hi @sukhchainn and thanks for the question

@BenStigsen seems to have answered the question so I'll close the issue. If you have further comments, feel free to keep writing anyway.

FYI I have considered including grouping `|` but it will require a rewrite I think, because the current data-model is becoming stretched.

I am considering an implementation with 32-bit tokens as the regex_t elements, because it would enable encoding of more advanced features - at the cost of more memory-usage I'm afraid..
